language: haxe

haxe:
  - 3.4.7

env:
  - TARGET=flash
  - TARGET=html5

install:
  - haxelib git flixel https://github.com/HaxeFlixel/flixel

script:
  - haxe --cwd ~/haxe/lib/flixel/git/tests --run RunTravis flash new -install
  - haxe --run Script build $TARGET

after_success:
  - git fetch
  - git checkout -B master origin/master
  - haxe --run Script copy $TARGET ~/haxe/lib/flixel-demos/git/
  - bash deploy.sh
