name: build-demos-concurrently

on:
    push:
        branches: [master]
    workflow_dispatch:
    repository_dispatch:

jobs:
    get-demos:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                repository: 'HaxeFlixel/flixel-demos'
                submodules: 'recursive'
                ref: 'dev'
            - name: Find all demo folders
              id: find-demos
              run: |
                IFS=$'\n' read -d '' -r -a paths <<< "$(find . -type f -iname "project.xml" -exec dirname {} \; | sort -u)"
                echo "project-paths=${paths[*]}" >> $GITHUB_ENV
    build-demo:
        runs-on: ubuntu-latest
        needs: get-demos
        strategy:
            matrix:
                demo-path: ${{ needs.get-demos.outputs.project-paths }}
        steps:
            - run: echo ${{ matrix.demo-path }}