name: build-demos-concurrently

on:
    push:
        branches: [master]
    workflow_dispatch:
    repository_dispatch:

jobs:
    get-demos:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Checkout demos repository
              uses: actions/checkout@v4
              with:
                repository: 'HaxeFlixel/flixel-demos'
                submodules: 'recursive'
                ref: 'dev'
                clean: false
            - name: Find all demo folders
              uses: actions/github-script@v7
              id: find-demos
              with:
                result-encoding: string
                retries: 3
                script: |
                  const script = require("./js/getDemos.js");
                  script({core});
    build-demo:
        runs-on: ubuntu-latest
        needs: get-demos
        strategy:
            matrix:
                demo-path: ${{ needs.get-demos.outputs.project-paths }}
        steps:
            - run: echo ${{ matrix.demo-path }}