name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: "4.3.3"
    - uses: HaxeFlixel/setup-flixel@v1
      with:
        haxe-version: current
        flixel-versions: dev
        target: html5
    - run: haxe --run Script flash ${{env.HAXELIB_REPO}}/flixel-demos/git
    - run: haxe --run Script html5 ${{env.HAXELIB_REPO}}/flixel-demos/git
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./bin
        force_orphan: true
        cname: demos.haxeflixel.com
