name: CI

on:
  push:
    branches: [master]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: lix-pm/setup-lix@master
    - uses: HaxeFlixel/setup-flixel@master
      with:
        haxe-version: stable
        flixel-versions: dev
        target: html5
    - run: haxe --run Script flash ${{env.HAXELIB_REPO}}/flixel-demos/git
    - run: haxe --run Script html5 ${{env.HAXELIB_REPO}}/flixel-demos/git
    - uses: JamesIves/github-pages-deploy-action@3.4.3
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BRANCH: gh-pages
        FOLDER: bin
        SINGLE_COMMIT: true
